// Code generated by generate.sh. DO NOT EDIT.


package resource

// maxInt64Factors is the highest value that will be checked when removing factors of 10 from an int64.
// It is also the maximum decimal digits that can be represented with an int64.
_#maxInt64Factors: 18

_#mostNegative: -9223372036854775808

_#mostPositive: 9223372036854775807
