// Code generated by generate.sh. DO NOT EDIT.


package v1

import "time"

// Duration is a wrapper around time.Duration which supports correct
// marshaling to YAML and JSON. In particular, it marshals into strings, which
// can be used as map keys in json.
#Duration: {
	Duration: time.#Duration @protobuf(1,varint,opt,name=duration,casttype=time.Duration)
}
