// Code generated by generate.sh. DO NOT EDIT.


package watch

// Decoder allows StreamWatcher to watch any stream for which a Decoder can be written.
#Decoder: _

// Reporter hides the details of how an error is turned into a runtime.Object for
// reporting on a watch stream since this package may not import a higher level report.
#Reporter: _
