
// Code generated by generate.go. DO NOT EDIT.
package admission

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/admission/v1"
)


v1:  #AdmissionReview: kube.#AdmissionReview
v1:  #AdmissionReview: {
	kind: "AdmissionReview"
	apiVersion: "admission/v1"
}
