
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/admission/v1"
)


admission: v1:  kube.#AdmissionReview: {
	Kind: "AdmissionReview"
	apiVersion: "admission/v1"
}
