
// Code generated by generate.go. DO NOT EDIT.
package admission

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/admission/v1beta1"
)


v1beta1:  #AdmissionReview: kube.#AdmissionReview
v1beta1:  #AdmissionReview: {
	Kind: "AdmissionReview"
	apiVersion: "admission/v1beta1"
}
