
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/admissionregistration/v1"
)


admissionregistration: v1:  kube.#ValidatingWebhookConfiguration: {
	Kind: "ValidatingWebhookConfiguration"
	apiVersion: "admissionregistration/v1"
}

admissionregistration: v1:  kube.#MutatingWebhookConfiguration: {
	Kind: "MutatingWebhookConfiguration"
	apiVersion: "admissionregistration/v1"
}
