
// Code generated by generate.go. DO NOT EDIT.
package apiserverinternal

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/apiserverinternal/v1alpha1"
)


v1alpha1:  #StorageVersion: kube.#StorageVersion
v1alpha1:  #StorageVersion: {
	kind: "StorageVersion"
	apiVersion: "apiserverinternal/v1alpha1"
}
