
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/apiserverinternal/v1alpha1"
)


apiserverinternal: v1alpha1:  kube.#StorageVersion: {
	Kind: "StorageVersion"
	apiVersion: "apiserverinternal/v1alpha1"
}
