
// Code generated by generate.go. DO NOT EDIT.
package authentication

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/authentication/v1beta1"
)


v1beta1:  #TokenReview: kube.#TokenReview
v1beta1:  #TokenReview: {
	Kind: "TokenReview"
	apiVersion: "authentication/v1beta1"
}
