
// Code generated by generate.go. DO NOT EDIT.
package authentication

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/authentication/v1"
)


v1:  #TokenReview: kube.#TokenReview
v1:  #TokenReview: {
	Kind: "TokenReview"
	apiVersion: "authentication/v1"
}

v1:  #TokenRequest: kube.#TokenRequest
v1:  #TokenRequest: {
	Kind: "TokenRequest"
	apiVersion: "authentication/v1"
}
