
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/authentication/v1beta1"
)


authentication: v1beta1:  kube.#TokenReview: {
	Kind: "TokenReview"
	apiVersion: "authentication/v1beta1"
}
