
// Code generated by generate.go. DO NOT EDIT.
package autoscaling

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/autoscaling/v1"
)


v1:  #HorizontalPodAutoscaler: kube.#HorizontalPodAutoscaler
v1:  #HorizontalPodAutoscaler: {
	Kind: "HorizontalPodAutoscaler"
	apiVersion: "autoscaling/v1"
}

v1:  #Scale: kube.#Scale
v1:  #Scale: {
	Kind: "Scale"
	apiVersion: "autoscaling/v1"
}
