
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/autoscaling/v1"
)


autoscaling: v1:  #HorizontalPodAutoscaler: kube.#HorizontalPodAutoscaler
autoscaling: v1:  #HorizontalPodAutoscaler: {
	Kind: "HorizontalPodAutoscaler"
	apiVersion: "autoscaling/v1"
}

autoscaling: v1:  #Scale: kube.#Scale
autoscaling: v1:  #Scale: {
	Kind: "Scale"
	apiVersion: "autoscaling/v1"
}
