
// Code generated by generate.go. DO NOT EDIT.
package autoscaling

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/autoscaling/v2beta2"
)


v2beta2:  #HorizontalPodAutoscaler: kube.#HorizontalPodAutoscaler
v2beta2:  #HorizontalPodAutoscaler: {
	kind: "HorizontalPodAutoscaler"
	apiVersion: "autoscaling/v2beta2"
}
