
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/autoscaling/v2beta2"
)


autoscaling: v2beta2:  kube.#HorizontalPodAutoscaler: {
	Kind: "HorizontalPodAutoscaler"
	apiVersion: "autoscaling/v2beta2"
}
