
// Code generated by generate.go. DO NOT EDIT.
package autoscaling

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/autoscaling/v2beta1"
)


v2beta1:  #HorizontalPodAutoscaler: kube.#HorizontalPodAutoscaler
v2beta1:  #HorizontalPodAutoscaler: {
	Kind: "HorizontalPodAutoscaler"
	apiVersion: "autoscaling/v2beta1"
}
