
// Code generated by generate.go. DO NOT EDIT.
package batch

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/batch/v1"
)


v1:  #Job: kube.#Job
v1:  #Job: {
	kind: "Job"
	apiVersion: "batch/v1"
}
