
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/batch/v1"
)


batch: v1:  #Job: kube.#Job
batch: v1:  #Job: {
	Kind: "Job"
	apiVersion: "batch/v1"
}
