
// Code generated by generate.go. DO NOT EDIT.
package batch

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/batch/v1beta1"
)


v1beta1:  #JobTemplate: kube.#JobTemplate
v1beta1:  #JobTemplate: {
	Kind: "JobTemplate"
	apiVersion: "batch/v1beta1"
}

v1beta1:  #CronJob: kube.#CronJob
v1beta1:  #CronJob: {
	Kind: "CronJob"
	apiVersion: "batch/v1beta1"
}
