
// Code generated by generate.go. DO NOT EDIT.
package batch

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/batch/v2alpha1"
)


v2alpha1:  #JobTemplate: kube.#JobTemplate
v2alpha1:  #JobTemplate: {
	kind: "JobTemplate"
	apiVersion: "batch/v2alpha1"
}

v2alpha1:  #CronJob: kube.#CronJob
v2alpha1:  #CronJob: {
	kind: "CronJob"
	apiVersion: "batch/v2alpha1"
}
