
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/certificates/v1"
)


certificates: v1:  #CertificateSigningRequest: kube.#CertificateSigningRequest
certificates: v1:  #CertificateSigningRequest: {
	Kind: "CertificateSigningRequest"
	apiVersion: "certificates/v1"
}
