
// Code generated by generate.go. DO NOT EDIT.
package certificates

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/certificates/v1beta1"
)


v1beta1:  #CertificateSigningRequest: kube.#CertificateSigningRequest
v1beta1:  #CertificateSigningRequest: {
	Kind: "CertificateSigningRequest"
	apiVersion: "certificates/v1beta1"
}
