
// Code generated by generate.go. DO NOT EDIT.
package certificates

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/certificates/v1"
)


v1:  #CertificateSigningRequest: kube.#CertificateSigningRequest
v1:  #CertificateSigningRequest: {
	kind: "CertificateSigningRequest"
	apiVersion: "certificates/v1"
}
