
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/coordination/v1beta1"
)


coordination: v1beta1:  #Lease: kube.#Lease
coordination: v1beta1:  #Lease: {
	Kind: "Lease"
	apiVersion: "coordination/v1beta1"
}
