
// Code generated by generate.go. DO NOT EDIT.
package coordination

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/coordination/v1"
)


v1:  #Lease: kube.#Lease
v1:  #Lease: {
	Kind: "Lease"
	apiVersion: "coordination/v1"
}
