
// Code generated by generate.go. DO NOT EDIT.
package coordination

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/coordination/v1beta1"
)


v1beta1:  #Lease: kube.#Lease
v1beta1:  #Lease: {
	kind: "Lease"
	apiVersion: "coordination/v1beta1"
}
