
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/discovery/v1alpha1"
)


discovery: v1alpha1:  kube.#EndpointSlice: {
	Kind: "EndpointSlice"
	apiVersion: "discovery/v1alpha1"
}
