
// Code generated by generate.go. DO NOT EDIT.
package discovery

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/discovery/v1alpha1"
)


v1alpha1:  #EndpointSlice: kube.#EndpointSlice
v1alpha1:  #EndpointSlice: {
	kind: "EndpointSlice"
	apiVersion: "discovery/v1alpha1"
}
