
// Code generated by generate.go. DO NOT EDIT.
package discovery

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/discovery/v1beta1"
)


v1beta1:  #EndpointSlice: kube.#EndpointSlice
v1beta1:  #EndpointSlice: {
	kind: "EndpointSlice"
	apiVersion: "discovery/v1beta1"
}
