
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/events/v1"
)


events: v1:  #Event: kube.#Event
events: v1:  #Event: {
	Kind: "Event"
	apiVersion: "events/v1"
}
