
// Code generated by generate.go. DO NOT EDIT.
package events

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/events/v1"
)


v1:  #Event: kube.#Event
v1:  #Event: {
	kind: "Event"
	apiVersion: "events/v1"
}
