
// Code generated by generate.go. DO NOT EDIT.
package events

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/events/v1beta1"
)


v1beta1:  #Event: kube.#Event
v1beta1:  #Event: {
	Kind: "Event"
	apiVersion: "events/v1beta1"
}
