
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/flowcontrol/v1alpha1"
)


flowcontrol: v1alpha1:  kube.#FlowSchema: {
	Kind: "FlowSchema"
	apiVersion: "flowcontrol/v1alpha1"
}

flowcontrol: v1alpha1:  kube.#PriorityLevelConfiguration: {
	Kind: "PriorityLevelConfiguration"
	apiVersion: "flowcontrol/v1alpha1"
}
