
// Code generated by generate.go. DO NOT EDIT.
package flowcontrol

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/flowcontrol/v1alpha1"
)


v1alpha1:  #FlowSchema: kube.#FlowSchema
v1alpha1:  #FlowSchema: {
	kind: "FlowSchema"
	apiVersion: "flowcontrol/v1alpha1"
}

v1alpha1:  #PriorityLevelConfiguration: kube.#PriorityLevelConfiguration
v1alpha1:  #PriorityLevelConfiguration: {
	kind: "PriorityLevelConfiguration"
	apiVersion: "flowcontrol/v1alpha1"
}
