
// Code generated by generate.go. DO NOT EDIT.
package flowcontrol

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/flowcontrol/v1beta1"
)


v1beta1:  #FlowSchema: kube.#FlowSchema
v1beta1:  #FlowSchema: {
	Kind: "FlowSchema"
	apiVersion: "flowcontrol/v1beta1"
}

v1beta1:  #PriorityLevelConfiguration: kube.#PriorityLevelConfiguration
v1beta1:  #PriorityLevelConfiguration: {
	Kind: "PriorityLevelConfiguration"
	apiVersion: "flowcontrol/v1beta1"
}
