
// Code generated by generate.go. DO NOT EDIT.
package imagepolicy

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/imagepolicy/v1alpha1"
)


v1alpha1:  #ImageReview: kube.#ImageReview
v1alpha1:  #ImageReview: {
	kind: "ImageReview"
	apiVersion: "imagepolicy/v1alpha1"
}
