
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/imagepolicy/v1alpha1"
)


imagepolicy: v1alpha1:  kube.#ImageReview: {
	Kind: "ImageReview"
	apiVersion: "imagepolicy/v1alpha1"
}
