
// Code generated by generate.go. DO NOT EDIT.
package networking

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/networking/v1"
)


v1:  #NetworkPolicy: kube.#NetworkPolicy
v1:  #NetworkPolicy: {
	kind: "NetworkPolicy"
	apiVersion: "networking/v1"
}

v1:  #Ingress: kube.#Ingress
v1:  #Ingress: {
	kind: "Ingress"
	apiVersion: "networking/v1"
}

v1:  #IngressClass: kube.#IngressClass
v1:  #IngressClass: {
	kind: "IngressClass"
	apiVersion: "networking/v1"
}
