
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/networking/v1"
)


networking: v1:  kube.#NetworkPolicy: {
	Kind: "NetworkPolicy"
	apiVersion: "networking/v1"
}

networking: v1:  kube.#Ingress: {
	Kind: "Ingress"
	apiVersion: "networking/v1"
}

networking: v1:  kube.#IngressClass: {
	Kind: "IngressClass"
	apiVersion: "networking/v1"
}
