
// Code generated by generate.go. DO NOT EDIT.
package networking

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/networking/v1beta1"
)


v1beta1:  #Ingress: kube.#Ingress
v1beta1:  #Ingress: {
	Kind: "Ingress"
	apiVersion: "networking/v1beta1"
}

v1beta1:  #IngressClass: kube.#IngressClass
v1beta1:  #IngressClass: {
	Kind: "IngressClass"
	apiVersion: "networking/v1beta1"
}
