
// Code generated by generate.go. DO NOT EDIT.
package node

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/node/v1beta1"
)


v1beta1:  #RuntimeClass: kube.#RuntimeClass
v1beta1:  #RuntimeClass: {
	Kind: "RuntimeClass"
	apiVersion: "node/v1beta1"
}
