
// Code generated by generate.go. DO NOT EDIT.
package node

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/node/v1"
)


v1:  #RuntimeClass: kube.#RuntimeClass
v1:  #RuntimeClass: {
	kind: "RuntimeClass"
	apiVersion: "node/v1"
}
