
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/node/v1"
)


node: v1:  kube.#RuntimeClass: {
	Kind: "RuntimeClass"
	apiVersion: "node/v1"
}
