
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/policy/v1beta1"
)


policy: v1beta1:  kube.#PodDisruptionBudget: {
	Kind: "PodDisruptionBudget"
	apiVersion: "policy/v1beta1"
}

policy: v1beta1:  kube.#Eviction: {
	Kind: "Eviction"
	apiVersion: "policy/v1beta1"
}

policy: v1beta1:  kube.#PodSecurityPolicy: {
	Kind: "PodSecurityPolicy"
	apiVersion: "policy/v1beta1"
}
