
// Code generated by generate.go. DO NOT EDIT.
package scheduling

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/scheduling/v1alpha1"
)


v1alpha1:  #PriorityClass: kube.#PriorityClass
v1alpha1:  #PriorityClass: {
	Kind: "PriorityClass"
	apiVersion: "scheduling/v1alpha1"
}
