
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/scheduling/v1alpha1"
)


scheduling: v1alpha1:  kube.#PriorityClass: {
	Kind: "PriorityClass"
	apiVersion: "scheduling/v1alpha1"
}
