
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/scheduling/v1beta1"
)


scheduling: v1beta1:  #PriorityClass: kube.#PriorityClass
scheduling: v1beta1:  #PriorityClass: {
	Kind: "PriorityClass"
	apiVersion: "scheduling/v1beta1"
}
