
// Code generated by generate.go. DO NOT EDIT.
package scheduling

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/scheduling/v1beta1"
)


v1beta1:  #PriorityClass: kube.#PriorityClass
v1beta1:  #PriorityClass: {
	kind: "PriorityClass"
	apiVersion: "scheduling/v1beta1"
}
