
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/storage/v1"
)


storage: v1:  kube.#StorageClass: {
	Kind: "StorageClass"
	apiVersion: "storage/v1"
}

storage: v1:  kube.#VolumeAttachment: {
	Kind: "VolumeAttachment"
	apiVersion: "storage/v1"
}

storage: v1:  kube.#CSIDriver: {
	Kind: "CSIDriver"
	apiVersion: "storage/v1"
}

storage: v1:  kube.#CSINode: {
	Kind: "CSINode"
	apiVersion: "storage/v1"
}
