
// Code generated by generate.go. DO NOT EDIT.
package k8s

import (
	kube "github.com/delyvr/cue/k8s/gen/k8s.io/api/storage/v1alpha1"
)


storage: v1alpha1:  #VolumeAttachment: kube.#VolumeAttachment
storage: v1alpha1:  #VolumeAttachment: {
	Kind: "VolumeAttachment"
	apiVersion: "storage/v1alpha1"
}

storage: v1alpha1:  #CSIStorageCapacity: kube.#CSIStorageCapacity
storage: v1alpha1:  #CSIStorageCapacity: {
	Kind: "CSIStorageCapacity"
	apiVersion: "storage/v1alpha1"
}
