// Code generated by generate.sh. DO NOT EDIT.


package runtime

// UnstructuredConverter is an interface for converting between interface{}
// and map[string]interface representation.
#UnstructuredConverter: _
