// Code generated by generate.sh. DO NOT EDIT.


package runtime

// NegotiateError is returned when a ClientNegotiator is unable to locate
// a serializer for the requested operation.
#NegotiateError: {
	ContentType: string
	Stream:      bool
}
